term.setCursorPos(1,8)
print("---Menu---")
print("|Run     |")
print("|Unins...|")
print("|Shell   |")
print("|        |")
print("|        |")
print("|Reboot  |")
print("|Shutdown|")
print("----------")
